# Generated by Django 6.0.3 on 2026-04-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fabric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название ткани"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="fabrics/", verbose_name="Фото образца"
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        max_length=50, verbose_name="Страна (Турция, Россия и т.д.)"
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False, verbose_name="Показывать на главной?"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок вывода"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ткань",
                "verbose_name_plural": "Ткани",
                "ordering": ["position"],
            },
        ),
    ]
