# Generated by Django 6.0.3 on 2026-04-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fabric",
            name="brand",
            field=models.CharField(
                blank=True,
                default="Premium Quality",
                max_length=100,
                verbose_name="Бренд/Мануфактура",
            ),
        ),
        migrations.AddField(
            model_name="fabric",
            name="composition",
            field=models.CharField(
                default="100% Wool", max_length=100, verbose_name="Состав"
            ),
        ),
        migrations.AddField(
            model_name="fabric",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание для каталога"),
        ),
        migrations.AddField(
            model_name="fabric",
            name="price_category",
            field=models.CharField(
                choices=[
                    ("standard", "Standard ($150)"),
                    ("premium", "Premium ($350)"),
                ],
                default="premium",
                max_length=20,
                verbose_name="Ценовая категория",
            ),
        ),
        migrations.AlterField(
            model_name="fabric",
            name="origin",
            field=models.CharField(
                choices=[
                    ("Китай", "Китай"),
                    ("Турция", "Турция"),
                    ("Италия", "Италия"),
                    ("Россия", "Россия"),
                ],
                max_length=50,
                verbose_name="Страна производства",
            ),
        ),
    ]
