# Generated by Django 6.0.3 on 2026-05-01 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_fabric_brand_fabric_composition_fabric_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fabric",
            options={"verbose_name": "Ткань", "verbose_name_plural": "Ткани"},
        ),
        migrations.RenameField(
            model_name="fabric",
            old_name="is_popular",
            new_name="show_on_main",
        ),
        migrations.RemoveField(
            model_name="fabric",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="fabric",
            name="image",
        ),
        migrations.RemoveField(
            model_name="fabric",
            name="origin",
        ),
        migrations.RemoveField(
            model_name="fabric",
            name="position",
        ),
        migrations.RemoveField(
            model_name="fabric",
            name="price_category",
        ),
        migrations.AddField(
            model_name="fabric",
            name="category",
            field=models.CharField(
                default="premium", max_length=100, verbose_name="Ценовая категория"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fabric",
            name="country",
            field=models.CharField(
                default="Италия", max_length=100, verbose_name="Страна производства"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fabric",
            name="main_image",
            field=models.ImageField(
                default="", upload_to="fabrics/", verbose_name="Основное фото образца"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fabric",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Порядок вывода"),
        ),
        migrations.AlterField(
            model_name="fabric",
            name="composition",
            field=models.TextField(verbose_name="Состав"),
        ),
        migrations.AlterField(
            model_name="fabric",
            name="description",
            field=models.TextField(verbose_name="Описание для каталога"),
        ),
        migrations.AlterField(
            model_name="fabric",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название ткани"),
        ),
        migrations.CreateModel(
            name="FabricImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="fabrics/gallery/",
                        verbose_name="Дополнительный цвет/фото",
                    ),
                ),
                (
                    "fabric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="mainapp.fabric",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дополнительное фото",
                "verbose_name_plural": "Дополнительные фото",
            },
        ),
    ]
