# Generated by Django 6.0.3 on 2026-05-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_fabric_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=255, verbose_name="Имя клиента"),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(unique=True, verbose_name="ID в Telegram"),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Username Telegram",
                    ),
                ),
                (
                    "selected_fabric",
                    models.CharField(max_length=255, verbose_name="Выбранная ткань"),
                ),
                (
                    "measurements_data",
                    models.TextField(verbose_name="Мерки по инструкции"),
                ),
                (
                    "client_comment",
                    models.TextField(blank=True, verbose_name="Пожелания клиента"),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Итоговая цена ($)",
                    ),
                ),
                (
                    "is_commission_received",
                    models.BooleanField(
                        default=False, verbose_name="Мой процент получен"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый заказ (Ожидание закройщика)"),
                            ("confirmed", "Подтвержден / В пошиве"),
                            ("ready", "Готов к отправке"),
                            ("completed", "Завершен"),
                            ("canceled", "Отменен"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее изменение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created_at"],
            },
        ),
    ]
