# Generated by Django 6.0.3 on 2026-05-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="telegram_id",
            field=models.BigIntegerField(verbose_name="ID в Telegram"),
        ),
    ]
