# Generated by Django 6.0.3 on 2026-05-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_alter_order_telegram_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="fabric",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=300,
                max_digits=10,
                verbose_name="Цена за костюм ($)",
            ),
        ),
    ]
